// 500 Shakespearean insults — real lines and faithful adaptations from across the canon.
// Shown while waiting for a villain to be summoned.

export const SHAKESPEAREAN_INSULTS = [
  // Othello
  "Thou art a boil, a plague sore!",
  "Thou art as jealous as a Turk.",
  "You are a villain! A whitewashing rogue!",
  "Thy jealousy doth shape faults that are not.",
  "Thou dost conspire against thy friend.",
  "Thou prick-eared cur of Iceland!",

  // Titus Andronicus
  "Villain, I have done thy mother.",
  "Thou map of woe, that thus dost talk in signs!",
  "Thou art a Roman; be not barbarous.",
  "Away, inhuman dog! Unhallowed slave!",

  // Henry IV & V
  "Thou art as fat as butter.",
  "Away, you scullion! You rampallian! You fustilarian!",
  "There's no more faith in thee than in a stewed prune.",
  "Thou hast no more brain than I have in mine elbows.",
  "Thou art essentially a natural coward without instinct.",
  "Thou whoreson, obscene, greasy tallow-catch!",
  "Thou clay-brained guts, thou knotty-pated fool!",
  "That trunk of humours, that stuffed cloak-bag of guts!",
  "Thou art violently carried away from grace.",
  "I scorn you, scurvy companion!",
  "You starved blood-hound!",
  "Thou cream-faced loon!",
  "Out of my sight! Thou dost infect my eyes.",
  "Go, prick thy face, and over-red thy fear, thou lily-livered boy!",
  "Thou art a honeysuckle villain.",
  "Peace, ye fat-kidneyed rascal!",
  "Hang thyself in thine own heir-apparent garters!",
  "You Bull's-pizzle, you stock-fish!",

  // As You Like It
  "I do desire we may be better strangers.",
  "Sell when you can; you are not for all markets.",
  "Thou art in a parlous state, shepherd.",
  "Your brain is as dry as the remainder biscuit after a voyage.",
  "I will kill thee a hundred and fifty ways.",

  // King Lear
  "A knave; a rascal; an eater of broken meats!",
  "Thou whoreson zed! Thou unnecessary letter!",
  "Away! The foul fiend follows me!",
  "Thou art a lady; if only to go warm were gorgeous.",
  "He's mad that trusts in the tameness of a wolf.",
  "Down, thou climbing sorrow!",
  "The prince of darkness is a gentleman.",
  "Thou changed and self-covered thing, for shame!",
  "Thou art a soul in bliss; I am bound upon a wheel of fire.",
  "Thou side-piercing sight!",

  // The Merry Wives of Windsor
  "Thou art the Mars of malcontents!",
  "I cannot tell what the dickens his name is.",
  "You Banbury cheese!",
  "Thou art not altogether a fool.",

  // Hamlet
  "Frailty, thy name is woman!",
  "More of your conversation would infect my brain.",
  "Thou wretched, rash, intruding fool, farewell!",
  "You are a fishmonger.",
  "Thou mixture rank, of midnight weeds collected.",
  "Bloody, bawdy villain! Remorseless, treacherous, lecherous, kindless villain!",
  "There are more things in heaven and earth than are dreamt of in thy philosophy.",
  "One may smile, and smile, and be a villain.",
  "The lady doth protest too much.",
  "Thou dost lie in 't, to be in 't and say it is thine.",
  "Thou art e'en as just a man as e'er my conversation coped withal — NOT.",
  "Get thee to a nunnery!",
  "Thrift, thrift, Horatio! The funeral baked meats did coldly furnish forth the marriage tables.",

  // Richard III
  "Thou elvish-marked, abortive, rooting hog!",
  "Thou poisonous bunch-backed toad!",
  "Thou mis-shapen Dick!",
  "Thou lump of foul deformity!",
  "Out of my sight! Thou dost infect mine eyes!",
  "Thou toad, thou toad!",
  "Thou slave of nature and the son of hell!",
  "Thou rag of honour! Thou detested —",
  "Foul wrinkled witch, what makest thou in my sight?",
  "Thou cacodemon! There thy kingdom is.",
  "Poor painted queen, vain flourish of my fortune!",
  "Was ever woman in this humour wooed?",
  "Thou bottled spider!",

  // The Tempest
  "Thou most lying slave!",
  "Thou earth! Thou tortoise!",
  "A pox o' your throat, you bawling, blasphemous, incharitable dog!",
  "Thou jesting monkey, thou!",
  "You taught me language; and my profit on 't is, I know how to curse.",
  "Thou deboshed fish, thou!",
  "Hag-seed, hence!",
  "Abhorred slave, which any print of goodness wilt not take!",

  // Macbeth
  "Thou art unfit for any place but hell.",
  "The devil himself could not pronounce a title more hateful.",
  "What, you egg? Young fry of treachery!",
  "Go, prick thy face!",
  "Thou lily-livered boy!",
  "Thou cream-faced loon! Where got'st thou that goose look?",
  "Thy bones are marrowless, thy blood is cold.",
  "Thou hast no speculation in those eyes!",
  "Not in the legions of horrid hell can come a devil more damned.",
  "Thou saucy, frothy boy!",

  // A Midsummer Night's Dream
  "Thou painted maypole!",
  "Get you gone, you dwarf!",
  "Thou cat, thou burr! Vile thing, let me loose!",
  "O spite! O hell! I see you are all bent to set against me.",
  "Out, dog! Out, cur! Thou drivest me past the bounds of maiden's patience.",
  "What hempen homespuns have we swaggering here?",
  "Lord, what fools these mortals be!",

  // Twelfth Night
  "Better a witty fool than a foolish wit.",
  "Dost thou think, because thou art virtuous, there shall be no more cakes and ale?",
  "Go hang yourselves all! You are idle, shallow things.",
  "Some are born great, some achieve greatness, and some have greatness thrown upon them — none of which applies to thee.",
  "Thou art as wise as thou art beautiful — which is to say, not at all.",

  // The Taming of the Shrew
  "Thy tongue outvenoms all the worms of Nile.",
  "Thou flea, thou nit, thou winter-cricket, thou!",
  "You peasant swain! You whoreson malt-horse drudge!",
  "Thou hast undone our mother.",
  "Away, you three-inch fool!",
  "You logger-headed and unpolished grooms!",

  // Troilus and Cressida
  "Thou art bought and sold among those of any wit, like a barbarian slave.",
  "Thou crusty batch of nature!",
  "Thou thing of no bowels, thou!",
  "Thou idle immaterial skein of sleave-silk!",
  "Thou hast no more brain than a stone.",
  "Thou full dish of fool!",
  "He has not so much brain as ear-wax.",
  "Thou mongrel beef-witted lord!",
  "Thou stool for a witch!",
  "Thou sodden-witted lord!",
  "Thou hast no more brain than I have in mine elbows.",

  // Coriolanus
  "Thou herd of — boils and plagues plaster you o'er!",
  "You common cry of curs! Whose breath I hate!",
  "You souls of geese, that bear the shapes of men!",
  "Thou rotten thing!",
  "The tartness of his face sours ripe grapes.",
  "You are the musty chaff, and you are smelt above the moon.",

  // Julius Caesar
  "Thou hast described a hot friend cooling.",
  "You blocks, you stones, you worse than senseless things!",
  "Yond Cassius has a lean and hungry look; he thinks too much.",
  "Et tu, Brute? — the most unkindest cut of all.",
  "Cowards die many times before their deaths; the valiant never taste of death but once.",

  // Romeo and Juliet
  "Thou art like a toad — ugly and venomous.",
  "A plague o' both your houses!",
  "You kiss by the book.",
  "Thou wilt quarrel with a man for cracking nuts.",
  "Thy head is as full of quarrels as an egg is full of meat.",

  // The Merchant of Venice
  "The devil can cite Scripture for his purpose.",
  "Thou naughty jailer, that thou art so fond to come abroad with him!",
  "If I can catch him once upon the hip, I will feed fat the ancient grudge I bear him.",
  "It is a wise father that knows his own child.",
  "Thou art too wild, too rude and bold of voice.",

  // Much Ado About Nothing
  "I wonder that you will still be talking; nobody marks you.",
  "Would thou wert clean enough to spit upon!",
  "Thou art a villain; I jest not.",
  "Thou pure impiety and impious purity!",
  "I had rather hear my dog bark at a crow than a man swear he loves me.",
  "You have such a February face, so full of frost, of storm, and cloudiness.",

  // Measure for Measure
  "Thy sin's not accidental, but a trade.",
  "Thou art a flesh-monger, a fool, and a coward.",
  "Thine face is not worth sunburning.",
  "They say best men are moulded out of faults.",
  "Thou hast nor youth nor age, but as it were an after-dinner's sleep.",
  "O, what may man within him hide, though angel on the outward side!",

  // The Winter's Tale
  "Thou want'st a rough pash and the shoots that I have, to be full like me.",
  "I am a feather for each wind that blows.",
  "Thou dost make possible things not so held.",
  "A sad tale's best for winter.",
  "Go, play, boy, play: thy mother plays, and I play too.",

  // Cymbeline
  "Thou basest thing, avoid hence, from my sight!",
  "Thou injurious thief, hear but my name and tremble!",
  "Thou venomous toad! Thou detested kite!",
  "Thou runaway, thou coward!",

  // All's Well That Ends Well
  "A young man married is a man that's marred.",
  "Thou art not honest; thou art not good.",
  "Go to, sir; you were beaten in Italy for picking a kernel out of a pomegranate.",
  "Your old virginity is like one of our French withered pears: it looks ill, it eats drily.",

  // Timon of Athens
  "I am sick of this false world.",
  "More man? Plague, plague!",
  "Thou disease of a friend!",
  "Uncover, dogs, and lap!",
  "Live loathed and long, most smiling, smooth, detested parasites!",
  "Men shut their doors against a setting sun.",
  "What viler thing upon the earth than friends who can bring noblest minds to basest ends?",
  "I am misanthropos, and hate mankind.",

  // Henry VI Parts 1-3
  "Thou art neither like thy sire nor dam.",
  "O tiger's heart wrapped in a woman's hide!",
  "Down, down to hell; and say I sent thee thither!",
  "The smallest worm will turn, being trodden on.",
  "Thou setter up and plucker down of kings!",
  "Thou rag of honour! Thou detested —",

  // Two Gentlemen of Verona
  "Thou subtle, perjured, false, disloyal man!",
  "He is complete in feature and in mind with all good grace to grace a gentleman.",
  "Thou counterfeit to thy true friend!",

  // Antony and Cleopatra
  "Age cannot wither her, nor custom stale her infinite variety — but it hath withered thee.",
  "Thou art the armourer of my heart. False, false!",
  "I have yet room for six scotches more.",
  "You have been a boggler ever.",
  "Triple-turned whore!",
  "The shirt of Nessus is upon me.",

  // King John
  "Thou slave, thou wretch, thou coward!",
  "Thou wear a lion's hide! Doff it for shame!",
  "Thou odoriferous stench! Sound rottenness!",
  "Thou unadvised scold!",
  "Mad world! Mad kings! Mad composition!",

  // Richard II
  "A lunatic lean-witted fool!",
  "The tongues of dying men enforce attention like deep harmony.",
  "Thou art a traitor and a miscreant!",
  "Not all the water in the rough rude sea can wash the balm off from an anointed king.",
  "Thou rascal beadle, hold thy bloody hand!",

  // The Comedy of Errors
  "Thou drone, thou snail, thou slug, thou sot!",
  "Mome, malt-horse, capon, coxcomb, idiot, patch!",
  "I think thou art an ass.",
  "There's no time for a man to recover his hair that grows bald by nature.",

  // Love's Labour's Lost
  "Thou halfpenny purse of wit, thou pigeon-egg of discretion!",
  "More fools thou! — to be foresworn is worse than to be a villain.",
  "They have been at a great feast of languages, and stolen the scraps.",
  "He draweth out the thread of his verbosity finer than the staple of his argument.",

  // Pericles
  "Thou speak'st like him 's untutored to repeat.",
  "Thou show'st a noble vessel: what's within thee?",
  "Thy deeds are poison to my blood.",

  // Henry VIII
  "Thou art a proud traitor, priest!",
  "Those twins of learning that he raised in you — Ipswich and Oxford — one fell with him.",
  "Thou scarlet sin!",
  "Had I but served my God with half the zeal I served my king, he would not in mine age have left me naked to mine enemies.",
  "Press not a falling man too far!",

  // The Merry Wives of Windsor (additional)
  "Thou globe of sinful continents!",
  "Thou hast the right arched beauty of the brow.",
  "Out of my door, you witch, you rag, you baggage!",

  // Sonnets & Poems — adapted as insults
  "When I consider every thing that grows holds in perfection but a little moment — especially thee.",
  "Thy glass will show thee how thy beauties wear — poorly.",
  "For where is she so fair whose uneared womb disdains the tillage of thy husbandry? Nowhere.",

  // More from across the canon — vivid, punchy, memorable
  "Thou art the best of the cut-throats.",
  "Thou loggerhead! Thou unmannered slave!",
  "You abilities are too infant-like for doing much alone.",
  "Thou dost infect my eyes!",
  "You are as a candle, the better part burnt out.",
  "Thou disease of a friend!",
  "Thou art a most notable coward, an infinite and endless liar.",
  "You are not worth the dust which the rude wind blows in your face.",
  "The first thing we do, let's kill all the lawyers — starting with thee.",
  "Thou art a natural coward without instinct.",
  "I am pigeon-livered and lack gall.",
  "Thou art a base, proud, shallow, beggarly, three-suited, hundred-pound, filthy, worsted-stocking knave!",
  "Thou art a Castilian King urinal!",
  "You starvelling, you elf-skin, you dried neat's tongue!",
  "Go, thou art made like a goose.",
  "Thou hast the most unsavoury similes.",
  "Thou leathern-jerkin, crystal-button, knot-pated, agate-ring, puke-stocking, caddis-garter, smooth-tongue, Spanish-pouch!",
  "Thou art a three-suited, hundred-pound, filthy worsted-stocking rogue!",
  "Thy mother's of my generation: what's she, if I be a dog?",
  "You Banbury cheese!",
  "Thou unfit for any place but hell.",
  "You juggler! You canker-blossom!",
  "You counterfeit, you puppet, you!",
  "Thou damned and luxurious mountain goat!",
  "There is no more mercy in him than there is milk in a male tiger.",
  "Thou odious stench!",
  "Would thou wert clean enough to spit upon!",
  "Thou pribbling, ill-breeding miscreant!",
  "More of your conversation would infect my brain.",
  "Thou bawdy, hell-hated foot-licker!",
  "Thou cockered, idle-headed hugger-mugger!",
  "I'll beat thee, but I would infect my hands.",
  "Thou currish, fly-bitten codpiece!",
  "You are thought here to be the most senseless and fit man for the constable of the watch.",
  "Your means are very slender, and your waste is great.",
  "Thou art the rudeliest welcome to this world.",
  "Out, you green-sickness carrion! Out, you baggage!",
  "You are pictures out of doors, bells in your parlours, wild-cats in your kitchens.",
  "Saints in your injuries, devils being offended.",
  "Thou didst make children — and wilt not support them. Villain!",
  "Thou hast pared thy wit o' both sides, and left nothing i' the middle.",
  "Thou churlish, common-kissing measle!",
  "Away, you mouldy rogue, away!",
  "You scurvy, old, filthy, scurvy lord!",
  "Thou mangled, toad-spotted traitor!",
  "Thou unweighing, urchin-snouted wretch!",
  "Thou impertinent, motley-minded coxcomb!",
  "You, minion, are too saucy.",
  "Thou wimpled, idle-headed gudgeon!",
  "Out, you mad-headed ape! A weasel hath not such a deal of spleen as you are tossed with.",
  "Thou errant, rump-fed hedge-pig!",
  "You ruinous butt of malmsey!",
  "Thou loggerheaded, flap-mouthed varlet!",
  "Thou wayward, knotty-pated foot-licker!",
  "You poor, decayed, ingenious, foolish, rascally knave!",
  "Your virginity breeds mites, much like a cheese.",
  "Thou surfeited, shard-borne boar-pig!",
  "How now, you whoreson peasant! Dost thou call me 'fool'?",
  "Thou rank, pottle-deep drunkard!",
  "Away, you cut-purse rascal! You filthy bung!",
  "Thou clouted, tardy-gaited pigeon-egg!",
  "Thou yeasty, fool-born miscreant!",
  "You foul defacer of God's handiwork!",
  "Thou bawdy, bat-fowling canker-blossom!",
  "The rankest compound of villainous smell that ever offended nostril.",
  "You thread! You thimble!",
  "You, sir, are undone — no, not by me, by your own vileness.",
  "Thou gleeking, earth-vexing death-token!",
  "Away, you rogue! Dost thou not know me?",
  "Thou reeky, rump-fed barnacle!",
  "He is deformed, crooked, old, and sere.",
  "Thou roguish, hedge-born flirt-gill!",
  "Away, you thin thing; away, you rascal!",
  "Your wit's too hot, it speeds too fast, 'twill tire.",
  "Thou lumpish, beetle-headed dewberry!",
  "You whoreson cullionly barbermonger!",
  "Thou gorbellied, onion-eyed ratsbane!",
  "You rogue! You rascal!",
  "Thou pribbling, rump-fed pignut!",
  "Thou puking, boil-brained clot-pole!",
  "Away, you three-inch fool!",
  "Thou craven, milk-livered caitiff!",
  "You are a tedious fool.",
  "Thou art a boil upon the face of this fair earth.",
  "Better a witty fool than a foolish wit — thou art neither.",
  "Thou jarring, dread-bolted moldwarp!",
  "You are thought here to be the most senseless and fit man for the job — and even that is generous.",
  "Thou art the son and heir of a mongrel bitch.",
  "Thou froward, hasty-witted haggard!",
  "Thou art a most pernicious usurer.",
  "Thine horrid image doth unfix my hair.",
  "Thou wilt be as valiant as the wrathful dove or most magnanimous mouse.",
  "Thou infectious, plume-plucked popinjay!",
  "You are the hare of whom the proverb goes: his valour preys on sleeping cats.",
  "Thou caluminous, doghearted dewdrop!",
  "I do wish thou wert a dog, that I might love thee something.",
  "Thou mammering, onion-eyed maggot-pie!",
  "Thou spongy, swag-bellied canker-blossom!",
  "You, sir, have neither heat, affection, limb, nor beauty, to make your marriage blest.",
  "Go shake your ears!",
  "Thou beslubber'd, knotty-pated foot-licker!",
  "Thou art a counterfeit cowardly knave.",
  "Out of my door! You witch, you hag, you baggage, you polecat, you ronyon!",
  "Your bum is the greatest thing about you.",
  "Thou art essentially mad, without seeming so.",
  "Thou paunchy, spur-galled codpiece!",
  "I would thou didst itch from head to foot and I had the scratching of thee.",
  "Thou warped, swag-bellied flap-dragon!",
  "Thou cockered, fen-sucked clotpole!",
  "You smell of old rags and stale mead.",
  "A most poor man, made tame to fortune's blows — that would be thee.",
  "You are the knight of the burning lamp — thy nose betrays thee.",
  "Thou tottering, fool-born fustilarian!",
  "I'll pray a thousand prayers for thy death.",
  "Thou art pigeon-livered and lackt gall.",
  "Your face, my thane, is as a book where men may read strange matters.",
  "Thou wolvish, half-faced fellow!",
  "You have a plentiful lack of wit.",
  "There's small choice in rotten apples — and thou art the worst of them.",
  "Thou fobbing, doghearted barnacle!",
  "You speak an infinite deal of nothing.",
  "Thou peevish, onion-eyed measle!",
  "Thou art neither fish nor flesh; a man cannot make thee yield.",
  "Your wit will not so soon out as another man's will; 'tis strongly wedged up in a block-head.",
  "Thou art a withered weed among fresh flowers.",
  "Thou droning, ill-breeding ratsbane!",
  "Thy wit is as thick as Tewkesbury mustard.",
  "Thou venomed, weather-bitten vassal!",
  "There is not ugly a fiend of hell as thou shalt be.",
  "Thou art a base football player!",
  "Thou goatish, beetle-headed dewberry!",
  "Thou yeasty, pox-marked minnow!",
  "Thou mewling, motley-minded maggot-pie!",
  "Thou art the running sore of all the land.",
  "You have such a February face.",
  "Thou lascivious, earth-vexing death-token!",
  "Thou shall be whipped with wire and stewed in brine.",
  "Thou vain, sheep-biting coxcomb!",
  "Thou canker of a calm world and a long peace!",
  "Thou impertinent, toad-spotted joithead!",
  "I had rather be a toad and live upon the vapour of a dungeon than keep a corner in the thing I love for others' uses — like thee.",
  "Thou burly-boned, clapper-clawed clack-dish!",
  "Thou villainous, ill-breeding miscreant!",
  "Thou spleeny, earth-vexing gudgeon!",
  "Thou art as loathsome as a toad.",
  "Thy food is such as hath been belched on by infected lungs.",
  "Thou qualling, weather-bitten death-token!",
  "Away, you bottle-ale rascal!",
  "Thou dankish, clay-brained bladder!",
  "Thou art the lid of a worm-eaten coffin.",
  "Thou puny, toad-spotted whey-face!",
  "Thou bawdy, bat-fowling canker-blossom!",
  "I have seen better faces in my time than stands on any shoulder that I see before me.",
  "You, mistress, all this coil is long of you.",
  "Thou caluminous, hedge-born measle!",
  "If thy speeches be true, we care not for thee.",
  "Thou art the Mars of malcontents — a poor, decayed, ingenious fool.",
  "Get thee glass eyes and, like a scurvy politician, seem to see the things thou dost not.",
  "Thou wayward, shard-borne malt-worm!",
  "The empty vessel makes the greatest sound — that would be thee.",
  "Thou churlish, ill-nurtured pignut!",
  "Thou frothy, tickle-brained strumpet!",
  "Thou loggerheaded, rump-fed horn-beast!",
  "False of heart, light of ear, bloody of hand — thou!",
  "Thou warped, flap-mouthed mumblecrust!",
  "Away, you Ethiope!",
  "Thou art a very ragged Wart.",
  "Thou roguish, fen-sucked canker-blossom!",
  "Thou hast a grim appearance, and thy face bears the character of woe.",
  "Thou ruttish, hasty-witted miscreant!",
  "Thou art the thing itself: unaccommodated man is no more but such a poor, bare, forked animal as thou art.",
  "Thou tottering, idle-headed scut!",
  "Thou art a tedious fool: to the purpose.",
  "Thou warped, pox-marked wagtail!",
  "Thou dissembling, shard-borne foot-licker!",
  "Thou jarring, bat-fowling bum-bailey!",
  "What a deformed thief this fashion is.",
  "Thou wimpled, plume-plucked varlet!",
  "Out, dunghill!",
  "Thou pribbling, pottle-deep popinjay!",
  "Thou craven, idle-headed mumblecrust!",
  "Thou gorbellied, plume-plucked pigeon-egg!",
  "Tempt not too much the hatred of my spirit, for I am sick when I do look on thee.",
  "Thou clapper-clawed, ill-nurtured measle!",
  "Thou rank, weather-bitten maggot-pie!",
  "Thou bawdy, fool-born bugbear!",
  "Thou qualling, swag-bellied dewberry!",
  "Thou villainous, rump-fed gudgeon!",
  "A pox on thee! Thou art a very superficial, ignorant, unweighing fellow.",
  "Thou beslubbering, rump-fed miscreant!",
  "Thou errant, weather-bitten moldwarp!",
  "I do repent the tedious minutes I with thee have spent.",
  "Thou hast a lean cheek and a blue eye — and neither suits thee.",
  "Thou saucy, motley-minded scut!",
  "Thou frothy, fen-sucked flap-dragon!",
  "Thou ruttish, earth-vexing harpy!",
  "Thou impertinent, bat-fowling varlot!",
  "Thou art a dead thing — a poor unmanned cloak.",
  "Thou pribbling, dread-bolted death-token!",
  "The plague of Greece upon thee, thou mongrel beef-witted lord!",
  "Thou lumpish, toad-spotted barnacle!",
  "Thou churlish, doghearted clotpole!",
  "Thou reeky, onion-eyed foot-licker!",
  "Thou spleeny, ill-breeding moldwarp!",
  "Thou art sharper than a serpent's tooth.",
  "Thou caluminous, hasty-witted horn-beast!",
  "Thy face is Lucifer's privy-kitchen.",
  "Thou surly, weather-bitten pignut!",
  "Thou wayward, bat-fowling flirt-gill!",
  "Thou fawning, half-faced malt-worm!",
  "Thou art the worst company I have kept.",
  "Thou craven, motley-minded clack-dish!",
  "More of thy ilk would make the world a cesspool.",
  "Thou jarring, fen-sucked bladder!",
  "Thou dissembling, fool-born mumblecrust!",
  "Thou infectious, pox-marked popinjay!",
  "Thou beslubber'd, boil-brained bum-bailey!",
  "Thou clouted, plume-plucked ratsbane!",
  "You take mine house when you do prop the beam that holds my neighbours — and give me not your hand.",
  "Thou peevish, ill-breeding maggot-pie!",
  "Thou gleeking, dread-bolted scut!",
  "Thou roguish, spur-galled harpy!",
  "Thou qualling, fool-born flirt-gill!",
  "Thou paunchy, fen-sucked pignut!",
  "Thou art a most pathetical break-promise.",
  "Thou beslubbering, swag-bellied fustilarian!",
  "Thou gorbellied, flap-mouthed joithead!",
  "Thou mangled, ill-breeding flap-dragon!",
  "I hold thee worse than an ale-washed hound in a lady's chamber.",
  "Thou loggerheaded, dread-bolted varlot!",
  "Thou currish, half-faced barnacle!",
  "Thou puking, knotty-pated death-token!",
  "Thou tottering, sheep-biting lewdster!",
  "Thou art as welcome as a pestilence.",
  "Thou rank, beetle-headed joithead!",
  "Thou surfeited, boil-brained clotpole!",
  "Thou art a villainous, abominable misleader of youth.",
  "Thou fobbing, toad-spotted measle!",
  "Thou mammering, flap-mouthed horn-beast!",
  "Thou reeky, earth-vexing fustilarian!",
  "Thou venomed, rump-fed minnow!",
  "Thou warped, onion-eyed ratsbane!",
];
